version: "3.9"

services:
  httrack-mcp:
    build: .
    container_name: httrack-mcp
    environment:
      - HTTRACK_MCP_PORT=3000
    ports:
      - "3000:3000"
      - "8080:8080"
    volumes:
      - downloads:/usr/src/app/downloads
    restart: unless-stopped

volumes:
  downloads: 